### ISSUE TITLE
Fails to build in app

### ISSUE THREAD

**Issue by BryanCrotaz** [sir-dunxalot/ember-cli-modernizr#3]
```
C:\projects\webcam>ember serve
version: 1.13.15
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
EISDIR, illegal operation on a directory
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:554:19)
    at Object.fs.readFileSync (fs.js:391:28)
    at ModernizrFilter.<anonymous> (C:\projects\webcam\node_modules\ember-cli-modernizr\lib\filter-files.js:170:20)
    at Array.forEach (native)
    at ModernizrFilter.updateCache (C:\projects\webcam\node_modules\ember-cli-modernizr\lib\filter-files.js:158:13)
    at C:\projects\webcam\node_modules\ember-cli-modernizr\node_modules\broccoli-caching-writer\index.js:95:21
    at lib$rsvp$$internal$$tryCatch (C:\projects\webcam\node_modules\ember-cli-modernizr\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:103
6:16)
    at lib$rsvp$$internal$$invokeCallback (C:\projects\webcam\node_modules\ember-cli-modernizr\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.
js:1048:17)
    at lib$rsvp$$internal$$publish (C:\projects\webcam\node_modules\ember-cli-modernizr\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019
:11)
```

**Comment by BryanCrotaz** [comment]
100% reproducible on a new Ember app

**Comment by sir-dunxalot** [comment]
Thanks for opening the issue. I will dig into it. It seems like there are a bunch of compatibility issues with 1.13+.
